### ISSUE TITLE
Observe에 ip좀 추가해주세요

### ISSUE THREAD

**Issue by darkness87** [darkness87/LwM2M#30]
해당 디바이스가 어떤 장치인지 가독성이 떨어집니다. ip로 구분하면 좀더 쉬울것 같습니다.

![image](https://user-images.githubusercontent.com/20449373/99350577-17af0c80-28e2-11eb-8bfe-b5ce86606c81.png)

확인 부탁드려요

**Comment by endless87** [comment]
Registration 과 Observation 정보 매핑하여 출력해야함

**Comment by endless87** [comment]
매핑하여 서버 적용 완료
