### ISSUE TITLE
Observe 취소가 안되는문제

### ISSUE THREAD

**Issue by darkness87** [darkness87/LwM2M#31]
Observe 수행중인 항목이 2개가 있지만 전체취소를 눌러서 수행했으나 0개 처리로 정리됩니다.

원인 파악 부탁드려요

![image](https://user-images.githubusercontent.com/20449373/99351313-aff9c100-28e3-11eb-889f-6fabc362ad64.png)

화면을 다시 돌아와도 개수는 똑같습니다.

![image](https://user-images.githubusercontent.com/20449373/99351264-9193c580-28e3-11eb-8e78-88e6b2519c82.png)

**Comment by endless87** [comment]
201번 클라이언트가 Observe 전체 취소시 취소가 안되는 문제가 발견...
로컬에서 클라이언트 2개 붙을 경우에 대하여 테스트 진행하였으나 이상없었음.
201번 클라이언트 최신버전 업데이트 또는 로그 제시 필요
